export const servicesContent = {
  heroSection: {
    SectionTitle: 'HERO_SECTION_TITLE',
    SectionSubtitle: 'HERO_SECTION_SUBTITLE',
  },
  serviceSection: {
    sectionTitle: 'SECTION_TITLE',
    sectionSubtitle: 'SECTION_SUBTITLE',
  },
  keyFeatureTitle: 'KEY_FEATURE_TITLE',
  services: [
    {
      id: 1,
      title: 'SERVICE_AGILE_TITLE',
      description: 'SERVICE_AGILE_DESCRIPTION',
      icon: '/assets/svg/agile.svg',
      featured: true,
      keyFeatures: [
        'SERVICE_AGILE_KEY_FEATURE_1',
        'SERVICE_AGILE_KEY_FEATURE_2',
        'SERVICE_AGILE_KEY_FEATURE_3',
      ],
    },
    {
      id: 2,
      title: 'SERVICE_AI_INNOVATIONS_TITLE',
      description: 'SERVICE_AI_INNOVATIONS_DESCRIPTION',
      icon: '/assets/svg/AI-Inovation.svg',
      featured: true,
      keyFeatures: [
        'SERVICE_AI_INNOVATIONS_KEY_FEATURE_1',
        'SERVICE_AI_INNOVATIONS_KEY_FEATURE_2',
        'SERVICE_AI_INNOVATIONS_KEY_FEATURE_3',
      ],
    },
    {
      id: 3,
      title: 'SERVICE_API_MANAGEMENT_TITLE',
      description: 'SERVICE_API_MANAGEMENT_DESCRIPTION',
      icon: '/assets/svg/API-Management.svg',
      featured: true,
      keyFeatures: [
        'SERVICE_API_MANAGEMENT_KEY_FEATURE_1',
        'SERVICE_API_MANAGEMENT_KEY_FEATURE_2',
        'SERVICE_API_MANAGEMENT_KEY_FEATURE_3',
      ],
    },
    {
      id: 4,
      title: 'SERVICE_APP_DEV_MANAGEMENT_TITLE',
      description: 'SERVICE_APP_DEV_MANAGEMENT_DESCRIPTION',
      icon: '/assets/svg/app-development.svg',
      featured: false,
      keyFeatures: [
        'SERVICE_APP_DEV_MANAGEMENT_KEY_FEATURE_1',
        'SERVICE_APP_DEV_MANAGEMENT_KEY_FEATURE_2',
        'SERVICE_APP_DEV_MANAGEMENT_KEY_FEATURE_3',
      ],
    },
    {
      id: 5,
      title: 'SERVICE_CLOUD_SOLUTIONS_TITLE',
      description: 'SERVICE_CLOUD_SOLUTIONS_DESCRIPTION',
      icon: '/assets/svg/cloud-solution.svg',
      featured: false,
      keyFeatures: [
        'SERVICE_CLOUD_SOLUTIONS_KEY_FEATURE_1',
        'SERVICE_CLOUD_SOLUTIONS_KEY_FEATURE_2',
        'SERVICE_CLOUD_SOLUTIONS_KEY_FEATURE_3',
      ],
    },
    {
      id: 6,
      title: 'SERVICE_DATA_INSIGHTS_TITLE',
      description: 'SERVICE_DATA_INSIGHTS_DESCRIPTION',
      icon: '/assets/svg/data-insight.svg',
      featured: false,
      keyFeatures: [
        'SERVICE_DATA_INSIGHTS_KEY_FEATURE_1',
        'SERVICE_DATA_INSIGHTS_KEY_FEATURE_2',
        'SERVICE_DATA_INSIGHTS_KEY_FEATURE_3',
      ],
    },
    {
      id: 7,
      title: 'SERVICE_CREATIVE_DESIGNS_TITLE',
      description: 'SERVICE_CREATIVE_DESIGNS_DESCRIPTION',
      icon: '/assets/svg/creative-design.svg',
      featured: false,
      keyFeatures: [
        'SERVICE_CREATIVE_DESIGNS_KEY_FEATURE_1',
        'SERVICE_CREATIVE_DESIGNS_KEY_FEATURE_2',
        'SERVICE_CREATIVE_DESIGNS_KEY_FEATURE_3',
      ],
    },
    {
      id: 8,
      title: 'SERVICE_DEVOPS_TITLE',
      description: 'SERVICE_DEVOPS_DESCRIPTION',
      icon: '/assets/svg/devops.svg',
      featured: false,
      keyFeatures: [
        'SERVICE_DEVOPS_KEY_FEATURE_1',
        'SERVICE_DEVOPS_KEY_FEATURE_2',
        'SERVICE_DEVOPS_KEY_FEATURE_3',
      ],
    },
    {
      id: 9,
      title: 'SERVICE_TRANSFORMATIVE_SOLUTIONS_TITLE',
      description: 'SERVICE_TRANSFORMATIVE_SOLUTIONS_DESCRIPTION',
      icon: '/assets/svg/transformative-solution.svg',
      featured: false,
      keyFeatures: [
        'SERVICE_TRANSFORMATIVE_SOLUTIONS_KEY_FEATURE_1',
        'SERVICE_TRANSFORMATIVE_SOLUTIONS_KEY_FEATURE_2',
        'SERVICE_TRANSFORMATIVE_SOLUTIONS_KEY_FEATURE_3',
      ],
    },
    {
      id: 10,
      title: 'SERVICE_STRATEGIC_CONSULTING_TITLE',
      description: 'SERVICE_STRATEGIC_CONSULTING_DESCRIPTION',
      icon: '/assets/svg/strategy-consulting.svg',
      featured: false,
      keyFeatures: [
        'SERVICE_STRATEGIC_CONSULTING_KEY_FEATURE_1',
        'SERVICE_STRATEGIC_CONSULTING_KEY_FEATURE_2',
        'SERVICE_STRATEGIC_CONSULTING_KEY_FEATURE_3',
      ],
    },
    {
      id: 11,
      title: 'SERVICE_SECURITY_TITLE',
      description: 'SERVICE_SECURITY_DESCRIPTION',
      icon: '/assets/svg/cyber-security.svg',
      featured: false,
      keyFeatures: [
        'SERVICE_SECURITY_KEY_FEATURE_1',
        'SERVICE_SECURITY_KEY_FEATURE_2',
        'SERVICE_SECURITY_KEY_FEATURE_3',
      ],
    },
    {
      id: 12,
      title: 'SERVICE_WEB_DEV_MANAGEMENT_TITLE',
      description: 'SERVICE_WEB_DEV_MANAGEMENT_DESCRIPTION',
      icon: '/assets/svg/web-dev.svg',
      featured: false,
      keyFeatures: [
        'SERVICE_WEB_DEV_MANAGEMENT_KEY_FEATURE_1',
        'SERVICE_WEB_DEV_MANAGEMENT_KEY_FEATURE_2',
        'SERVICE_WEB_DEV_MANAGEMENT_KEY_FEATURE_3',
      ],
    },
  ],
};
