// layout.tsx
import ThemeRegister from '@/theme/theme-register';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { Inter } from 'next/font/google';
import './globals.css';
import { getLangDir } from 'rtl-detect';
import { GoogleAnalytics } from '@next/third-parties/google';
import NavbarWrapper from '@/components/header/nav-wrapper';

const inter = Inter({ subsets: ['latin'] });

// TODO add on every page
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: ['/favicon.ico?v=4'],
    apple: ['/public/apple-touch-icon.png?v=4'],
    shortcut: ['/public/apple-touch-icon.png'],
  },
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  const direction = getLangDir(locale);
  return (
    <html
      dir={direction}
      lang={locale}
    >
      <ThemeRegister>
        <GoogleAnalytics gaId={process.env.GOOGLE_ANALYTICS_ID!} />
        <body className={inter.className}>
          <NextIntlClientProvider
            locale={locale}
            messages={messages}
          >
            <NavbarWrapper>{children}</NavbarWrapper>
          </NextIntlClientProvider>
        </body>
      </ThemeRegister>
    </html>
  );
}
